version: "2"
services:
  apigility:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:80"
    volumes:
     - .:/var/www
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  171.18.0.1/16